// <auto-generated />
namespace PCShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateProduct04072141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateProduct04072141));
        
        string IMigrationMetadata.Id
        {
            get { return "202307041442026_updateProduct04072141"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
