// <auto-generated />
namespace PCShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addMailField26723831s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMailField26723831s));
        
        string IMigrationMetadata.Id
        {
            get { return "202307261416352_addMailField26723831s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
