// <auto-generated />
namespace PCShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateorder1008231037 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorder1008231037));
        
        string IMigrationMetadata.Id
        {
            get { return "202308101539559_updateorder1008231037"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
