// <auto-generated />
namespace PCShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update17723530CH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update17723530CH));
        
        string IMigrationMetadata.Id
        {
            get { return "202307171031046_update17723530CH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
